### ISSUE TITLE
You guys gonna hack this into a package?

### ISSUE THREAD

**Issue by RobertLowe** [okgrow/rest2ddp#1]
This could be a helpful package. :D

Small FYI: `onCreateUser` can only be registered once! https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_server.js#L118

And where's the README at :P

Good job guys, you should feel really proud! <3

**Comment by pauldowman** [comment]
Definitely! Here's what I wrote in [our devpost submission](http://devpost.com/software/rest2ddp):

> We would like to see Meteor come to mind immediately for developers who are looking to put a new UI in front of a legacy app with a RESTful API, rather than being considered for new app development only. Front-end only frameworks tend to grow in popularity much faster than full-stack frameworks because there are so many developers with legacy apps that want to update the UI without rebuilding the entire app.
> 
> A hosted service is good for an API provider who wants to provide a DDP API without doing more work, it can be thought of like a proxy. But a developer who wants to consume a REST API might not want to go through a hosted proxy and might want to be able to subscribe to REST API's directly within their app.
> 
> So we would like to extract the core functionality into a package so that any Meteor app can easily subscribe to a REST API and receive live updates over DDP.

**Comment by RobertLowe** [comment]
Awesome!

**Comment by karldanninger** [comment]
Thanks @RobertLowe <3

**Comment by praneybehl** [comment]
:100:
