### ISSUE TITLE
best way to convert Strings into Date Objects

### ISSUE THREAD

**Issue by faceplant23** [okgrow/rest2ddp#10]
I really like this package, unfortunately I did not find a way to get the values from the returned JSON string converted to a date object.
Tried different formats in the rest output like   

```
'dateTest1' : ISODate("2016-01-26T11:55:01.947Z"),
'dateTest2' : Date("2016-01-26T11:55:01.947Z"),
'dateTest3' : 2016-01-26T11:55:01+01:00,
```

unfortunately they ended in an parse-error. So is there a nice way to get some, maybe in the config defined types as an object in the DDP output?

Thanks a lot

**Comment by benstr** [comment]
Can you use MomentJS to meet your need?

**Comment by faceplant23** [comment]
Hi benstr,
maybe I explained this not good enough. For sure it's not problem to convert a string into a date obj (something like `foo = Date("2016-01-26T11:55:01.947Z");` works fine) but I have not found a solution how to convert the objects in the collection.

I tried also the collections hooks package (which work fine for a normal collection) with things like:

```
Calendar = new Mongo.Collection('calendar'); //will get the calendar items from rest webservice

Calendar.before.insert(function (userId, doc) {
  doc.createdAt = Date.now();
});
//--> result: still no createdAt field in Calendar.find({}).collection..
```

The following coding took me a little further:

```
Calendar = new Mongo.Collection('calendar', {
  transform: function (doc) {
        doc.createdAt = new Date();
        doc.start= new Date(doc.start);
        doc.end= new Date(doc.end);
        return doc;
  },
});
```

but unfortunately this only transfoms the publication but not the items within the collection. So I still can not query the collection like `Calendar.find({createdAt: {$lt: new Date()} };`
Hope with the coding above my problem is a little clearer now.
Thanks in advance for a hint.

**Comment by rgould** [comment]
We've deprecated this package, therefore we're closing all open issues.
