### ISSUE TITLE
How to modfiy restUrl when response is strictly non-JSON 

### ISSUE THREAD

**Issue by scheung38** [okgrow/rest2ddp#14]
Due to legacy coding I have a response returned which is of the format:

200 {
    "records": [{
        "number": "CHG0xxxcxcx",
        "ticket_url": "https://myurl.mysite.com/nav_to.do?uri=change_request.do?sysparm_query=number%3DCHG0243882",
        "u_change_type": "Normal",
        "u_owner": "James Doe",
                :
                :
      }

So restUrl will still be able handle that? I am planning of using some temporary variable to strip out the 200 before the valid JSON object, but not sure how to go about handling this scenario? Thanks

**Comment by rgould** [comment]
We've deprecated this package, therefore we're closing all open issues.
