### ISSUE TITLE
setInterval can be a problem *in future*

### ISSUE THREAD

**Issue by gabrielhpugliese** [okgrow/rest2ddp#2]
http://stackoverflow.com/a/731625/1164249

It can enqueue too many jobs and lead to huge delays. Probably the best solution is push queues separate from application.

**Comment by karldanninger** [comment]
Yes, this is a good idea :) thanks

We ended up with setInterval due to time constraints for this hackathon

**Comment by rgould** [comment]
We've deprecated this package, therefore we're closing all open issues.
